language: java
jdk:
  - openjdk8

branches: # Travis CI를 어느 branch가 push될 때 수행할지 지정(현재 옵션은 오직 master에 push될 때만 수행)
  only:
    - master

#gradlew에 권한 부여
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache: # gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 동일한 의존성은 다음 배포때부터 다시 받지 않도록 설정
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # master에 push될 때 수행하는 명령어(현재 옵션은 프로젝트 내부에 둔 gradlew을 통해 clean & build 수행)

before_deploy: #deploy 명령어가 실행되기 전 수행, CodeDeploy는 JAR파일을 인식하지 못하므로 JAR + 기타 설정 파일들을 모아 압축
  - zip -r springboot-toy-api.zip . # 현재 위치의 모든 파일을 해당 이름으로 압축(명령어의 마지막 위치는 본인의 프로젝트 이름이어야 함)
  - mkdir -p deploy # deploy라는 디렉토리를 Travics CI가 실행중인 위치에 생성
  - mv springboot-toy-api.zip deploy/springboot-toy-api.zip # 해당 ***.zip파일을 deploy/***.zip으로 이동

#before_deploy:
#  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
#  - ls -al
#  - cp scripts/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp build/libs/*.jar before-deploy/
#  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
#  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
#  - mv before-deploy/before-deploy.zip deploy/toy-springboot2-webservice.zip # deploy로 zip파일 이동

deploy: # S#로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선택
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: toy-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: toy-springboot-build # S3 버킷
    key: springboot-toy-api.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: toy-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: toy-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications: # Travis CI 실행 완료 시 자동으로 알람 발송
  email:
    recipients:
      - hmyanghm@gmail.com